Json/valid cols
parseablehq/console pull request #299
Opened 2024-08-21 05:44 UTC by Koustavd18

Fix: This PR changes the JSON view to show the keys with a valid value

2024-08-22 05:56 UTC, balaji-jr requested changes
To find the valid headers you are iterating the log object twice which is unnecessary. 
And not clear why this is needed and why its included in the finding valid headers logic ?
`log[header] === null ? 'null'`

2024-08-22 10:20 UTC, balaji-jr requested changes

2024-08-22 10:20 UTC, balaji-jr commented on src/pages/Stream/Views/Explore/JSONView.tsx
> +	const validHeaders = headers.filter((header) => {
Why this iteration is necessary ?

2024-08-22 13:35 UTC, balaji-jr requested changes

2024-08-22 13:35 UTC, balaji-jr commented on src/pages/Stream/Views/Explore/JSONView.tsx
> +						if (!_.toString(log[header])) return;
Why not iterate over key-value pairs then?

2024-08-23 06:57 UTC, balaji-jr requested changes

2024-08-23 06:57 UTC, balaji-jr commented on src/pages/Stream/Views/Explore/JSONView.tsx
> +						//skiping fields with empty strings
Not sure why this is still needed.
If you are iterating over a log object, why you'd want to test whether its empty or not ?

2024-08-23 06:57 UTC, balaji-jr commented on src/pages/Stream/Views/Explore/JSONView.tsx
> +						if (!_.toString(value)) return;
empty line after exit condition.

2024-08-23 08:18 UTC, balaji-jr commented
I will address the remaining changes on https://github.com/parseablehq/console/pull/303

2024-08-23 08:18 UTC, balaji-jr submitted a review, later dismissed

2024-08-23 09:16 UTC, nikhilsinhaparseable approved these changes
looks good

2024-08-23 10:00 UTC, merged