Fix: Create User action
parseablehq/console pull request #309
Opened 2024-08-30 11:00 UTC by Koustavd18

### Description
The current create user modal allows to create user without any role specified.
This  PR makes sure that the create button is disabled unless the role is selected by the user

2024-09-02 09:36 UTC, balaji-jr requested changes

2024-09-02 09:36 UTC, balaji-jr commented on src/pages/AccessManagement/Users.tsx
> +	}, [SelectedRole, createUserInput]);
proper case for selectedRole

2024-09-02 09:36 UTC, balaji-jr commented on src/pages/AccessManagement/Users.tsx
>  			if (getRolesData?.data?.includes(SelectedRole)) {
This block can be a single statement

2024-09-03 05:47 UTC, balaji-jr commented
https://github.com/parseablehq/console/pull/309#discussion_r1740616126
This comment is not done yet but it's been resolved.

2024-09-03 05:48 UTC, balaji-jr approved these changes

2024-09-06 09:52 UTC, nikhilsinhaparseable approved these changes
looks good

2024-09-06 10:00 UTC, merged