Fix: Multiple queries were fired
parseablehq/console pull request #311
Opened 2024-09-02 08:11 UTC by Koustavd18

### Issue 
Multiple Queries were being fired

**Explanation**
Previously a logic was added to fetch footer count on change of time range . But the time range change function already includes a logic to refetch count and logs.

**Solution**
Removed the time range dependency from the useEffect function since the setTimeRange already cleans the store and sets currentPage to 0 which will initiate the refetch of both queryLogs and footer count

2024-09-02 09:27 UTC, balaji-jr requested changes
Mentioned issue is still reproducible

2024-09-09 10:37 UTC, Koustavd18 commented
Time Range duplication and multiple query for footer addressed. Mutiple query and time range duplication and for event Graph will be solved in a future PR

2024-09-09 20:26 UTC, balaji-jr requested changes

2024-09-09 20:26 UTC, balaji-jr commented on src/pages/Stream/Views/Explore/useLogsFetcher.ts
> +	useMemo(() => {
Redundant use of useMemo here

2024-09-09 20:26 UTC, balaji-jr commented on .gitignore
> +.vercel
We have a private deployment on Vercel for our convenience, making internal testing easier.
So, as discussed earlier rmv this line.

2024-09-11 08:00 UTC, closed without merging