Changes to copy button
parseablehq/console pull request #332
Opened 2024-09-30 06:29 UTC by Koustavd18

**Description**
The copy button is visible when a cell is empty in the logs view.
For in-secure context(HTTP) copy button is visible even though the clipboard is not accessible.

**FIXES**

- Copy button wont be visible when the cell value is empty in the logs table
- copy button and copy action will not be available for in-secure sessions

2024-09-30 07:40 UTC, balaji-jr requested changes

2024-09-30 07:48 UTC, balaji-jr commented
1. And we also need to handle the pop-up opening up on the right when selecting text. 
2. The same logic is required and should be implemented everywhere else. (Log info popup, stream info section etc ...)

2024-09-30 11:02 UTC, balaji-jr commented
As previously mentioned in https://github.com/parseablehq/console/pull/332#issuecomment-2382359993,

These 2 things are still not addressed.

2024-09-30 16:40 UTC, balaji-jr approved these changes

2024-10-01 18:21 UTC, nikhilsinhaparseable approved these changes
looks good

2024-10-02 09:34 UTC, merged