Dashboard add filters
parseablehq/console pull request #361
Opened 2024-11-07 11:37 UTC by praveen5959

2024-11-11 14:36 UTC, Koustavd18 requested changes

2024-11-12 06:22 UTC, praveen5959 commented on src/pages/Stream/providers/FilterProvider.tsx
> +		appliedFilterQuery: query,
Addressed this

2024-11-13 10:27 UTC, nikhilsinhaparseable submitted a review, later dismissed
approved, good to merge

2024-11-13 11:15 UTC, Koustavd18 approved these changes

2024-11-13 11:15 UTC, Koustavd18 commented on package.json
>  {
this file does not have any updates other than the indentations ..you can remove it from the commit

2024-11-18 11:36 UTC, merged