feat: Correlation feature
parseablehq/console pull request #394
Opened 2024-12-20 10:56 UTC by praveen5959

2024-12-20 11:11 UTC, praveen5959 commented
recheck

2024-12-24 12:11 UTC, Koustavd18 commented
Please update your vercel

2024-12-25 09:35 UTC, Koustavd18 requested changes
<img width="1678" alt="Screenshot 2024-12-25 at 3 04 32 PM" src="https://github.com/user-attachments/assets/dc751551-2f09-4c80-99f8-0c71131aaadd" />

Adding fields while other stream is loading renders an empty table

2024-12-26 08:10 UTC, Koustavd18 reviewed
<img width="1678" alt="Screenshot 2024-12-26 at 1 38 27 PM" src="https://github.com/user-attachments/assets/2bad9dd0-14cb-4ca5-85db-0f369cc7c017" />
same data for 2 different streams

2024-12-26 08:10 UTC, Koustavd18 requested changes
<img width="1678" alt="Screenshot 2024-12-26 at 1 40 15 PM" src="https://github.com/user-attachments/assets/dcc83041-41ab-4793-898d-6d39f5397d1b" />

multiple queries for same stream

2024-12-26 09:56 UTC, Koustavd18 commented on src/components/Navbar/index.tsx
> +										{navItem.route === CORRELATION_ROUTE ? (
active route can be handled with the predefined functions (same as other routes are handled)

2024-12-26 19:28 UTC, praveen5959 commented
> <img alt="Screenshot 2024-12-26 at 1 40 15 PM" width="1678" src="https://private-user-images.githubusercontent.com/78158736/398676574-dcc83041-41ab-4793-898d-6d39f5397d1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNDE1MDQsIm5iZiI6MTczNTI0MTIwNCwicGF0aCI6Ii83ODE1ODczNi8zOTg2NzY1NzQtZGNjODMwNDEtNDFhYi00NzkzLTg5OGQtNmQzOWY1Mzk3ZDFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDE5MjY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZmRjZGQ5MGQ4YzYwOTU2NTU5YmM0YzA1NWM4NTdmMDQwZWFkNzY4OTY3ODNjYzE4OTkyODI2ZTA4ZDk0ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U2U74pPJFynUvGgbXduRStiPBiKFBM7VD-Yuxeu3_SY">
> multiple queries for same stream

Any reproduction steps for this issue?

2024-12-27 06:34 UTC, Koustavd18 reviewed
There should be a disabled state if the field to correlate are not selected

2024-12-27 06:35 UTC, Koustavd18 reviewed
<img width="1678" alt="Screenshot 2024-12-27 at 12 01 58 PM" src="https://github.com/user-attachments/assets/5e319847-52a7-4ca4-a933-365f5145bd07" />
Fields are selected table is still empty
Also add check if the table is empty then the pagination section should not render

2024-12-27 06:37 UTC, Koustavd18 commented
Changing rows after correlating renders a empty table

2024-12-27 09:26 UTC, Koustavd18 requested changes
<img width="1678" alt="Screenshot 2024-12-27 at 2 53 42 PM" src="https://github.com/user-attachments/assets/7446b47d-b178-414f-8419-4a22515c90fc" />
After Selecting both streams I go to page 10 with rows set to 50 and then every log is incorrect

2025-01-02 06:07 UTC, Koustavd18 reviewed
Footer size changes on full screen mode

2025-01-02 06:23 UTC, Koustavd18 requested changes
Correlated Table should have a limit of 1000 and also fetch count to allow the user to change the offset
also display the count similar to logs table  view

2025-01-02 11:07 UTC, Koustavd18 commented
Export JSON and Export CSV not working

2025-01-02 11:08 UTC, Koustavd18 commented
<img width="1680" alt="Screenshot 2025-01-02 at 4 25 14 PM" src="https://github.com/user-attachments/assets/588bc079-f773-405b-9d6d-e0ebc602ff0e" />
Both Streams Boxes have the same colour in the sidebar

2025-01-02 11:12 UTC, Koustavd18 commented
Adding Second stream should not trigger a query call for the first stream

2025-01-09 06:38 UTC, Koustavd18 commented on src/components/SideBar/Sidebar.tsx
remove unused files

2025-01-09 06:39 UTC, Koustavd18 commented on src/components/SideBar/styles/SideBar.module.css
remove unused files

2025-01-09 06:41 UTC, Koustavd18 commented
remove queryEngine dependency

2025-01-09 06:44 UTC, Koustavd18 commented
correlation always adds the current Stream selected in the explore page even if the user does not click the add correlation btn

2025-01-09 09:08 UTC, Koustavd18 commented
Streams should have a Log limit of 250 but Correalted Logs should have a load limit of 1000

2025-01-09 09:11 UTC, Koustavd18 commented on src/pages/Correlation/providers/CorrelationProvider.tsx
> +	streamData?: Record<string, any>;
replace any with the expected types

2025-01-09 09:15 UTC, Koustavd18 commented on src/pages/Correlation/providers/CorrelationProvider.tsx
> +	tableOpts: {
are all table opts used in the correlation table?

2025-01-09 09:18 UTC, Koustavd18 commented on src/pages/Correlation/utils.ts
rm

2025-01-10 05:09 UTC, praveen5959 commented on src/pages/Correlation/providers/CorrelationProvider.tsx
> +	tableOpts: {
Not as of now but in future we may add the other functionalities.

2025-01-10 06:15 UTC, praveen5959 commented on src/components/Navbar/index.tsx
> +										{navItem.route === CORRELATION_ROUTE ? (
Handled it differently now

2025-01-13 15:20 UTC, nikhilsinhaparseable submitted a review, later dismissed
good to merge

2025-01-13 16:13 UTC, merged